# Generated by Django 2.2.1 on 2019-05-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleurl',
            name='shortcode',
            field=models.CharField(default='shorturl', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
