# Generated by Django 2.2.1 on 2019-05-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0003_auto_20190509_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
