# Generated by Django 2.2.1 on 2019-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0004_auto_20190509_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='simpleurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
