# Generated by Django 2.2.1 on 2019-05-11 13:39

from django.db import migrations, models
import simplify.validators


class Migration(migrations.Migration):

    dependencies = [
        ('simplify', '0007_auto_20190511_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleurl',
            name='url',
            field=models.CharField(max_length=220, validators=[simplify.validators.validate_url]),
        ),
    ]
